import { useEffect, useState } from 'react';
import { useAuth } from '@/context/AuthContext';
import { useToast } from '@/context/ToastContext';
import { Card, Button, Toggle, Badge, Skeleton, Input } from '@/components/ui';
import { Activity, RefreshCw, ShieldCheck, Zap, AlertTriangle, CheckCircle2, RotateCcw } from 'lucide-react';
import { getAIReliabilityStats, refreshOpenRouterModels, simulateAIRouterFailure, getAdminAIProviders, updateAdminAIProvider, testAdminAIProvider } from '@/lib/admin-services';
import { createSourceConnection, getSourceConnections, testSourceConnection } from '@/lib/services';
import type { AIOrchestratorResponse, AdminAIProvider, SourceConnection } from '@/types';

type Snapshot = Awaited<ReturnType<typeof getAIReliabilityStats>>;

const statusLabel: Record<string, string> = { HEALTHY: 'سليم', DEGRADED: 'متدهور', FAILING: 'يفشل', OFFLINE: 'متوقف', DISABLED: 'معطل', ACTIVE: 'نشط', COOLDOWN: 'تبريد', DEPRECATED: 'مهجور' };
const statusVariant = (status: string): 'success' | 'warning' | 'danger' | 'default' => status === 'HEALTHY' || status === 'ACTIVE' ? 'success' : status === 'DEGRADED' || status === 'COOLDOWN' ? 'warning' : status === 'FAILING' || status === 'OFFLINE' || status === 'DISABLED' || status === 'DEPRECATED' ? 'danger' : 'default';

export function AdminAIReliabilityPage() {
  const { user } = useAuth(); const { toast } = useToast();
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [simulation, setSimulation] = useState<AIOrchestratorResponse | null>(null);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [aiProviders, setAiProviders] = useState<AdminAIProvider[]>([]);
  const [providerKeys, setProviderKeys] = useState<Record<string, string>>({});
  const [providerBusy, setProviderBusy] = useState<string | null>(null);
  const [linkedinConnection, setLinkedinConnection] = useState<SourceConnection | null>(null);
  const [linkedinToken, setLinkedinToken] = useState('');
  const [linkedinBusy, setLinkedinBusy] = useState(false);

  const load = async () => { setLoading(true); try { setSnapshot(await getAIReliabilityStats()); } catch (error: any) { toast(error.message ?? 'تعذر تحميل مركز الاعتمادية', 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!user) return; getAdminAIProviders().then((providers) => setAiProviders(providers.filter((provider) => ['openrouter', 'groq', 'cerebras', 'mistral'].includes(provider.provider)))); getSourceConnections(user.id).then((connections) => setLinkedinConnection(connections.find((connection) => connection.source_code === 'linkedin') ?? null)); }, [user]);
  useEffect(() => { if (!autoRefresh) return; const timer = window.setInterval(load, 30000); return () => window.clearInterval(timer); }, [autoRefresh]);

  const saveAndTestProvider = async (provider: AdminAIProvider) => { if (!user || !providerKeys[provider.id]?.trim()) return; setProviderBusy(provider.id); try { await updateAdminAIProvider(user.id, provider.id, { api_key_input: providerKeys[provider.id].trim() }); const result = await testAdminAIProvider(user.id, provider.id); toast(result.message, result.success ? 'success' : 'error'); setProviderKeys((current) => ({ ...current, [provider.id]: '' })); await load(); } catch (error: any) { toast(error.message ?? 'تعذر حفظ مفتاح المزود', 'error'); } finally { setProviderBusy(null); } };
  const saveLinkedinToken = async () => { if (!user || !linkedinToken.trim()) return; setLinkedinBusy(true); try { const connection = await createSourceConnection(user.id, 'src-linkedin', 'LinkedIn', { access_token: linkedinToken.trim() }); setLinkedinConnection(connection); setLinkedinToken(''); const result = await testSourceConnection(user.id, connection.id); toast(result.message, result.success ? 'success' : 'error'); } catch (error: any) { toast(error.message ?? 'تعذر حفظ LinkedIn Token', 'error'); } finally { setLinkedinBusy(false); } };
  const refreshModels = async () => { if (!user) return; setBusy(true); try { const result = await refreshOpenRouterModels(user.id); toast(`تم تحديث ${result.free_models} نموذج مجاني من OpenRouter`, 'success'); await load(); } catch (error: any) { toast(error.message, 'error'); } finally { setBusy(false); } };
  const runSimulation = async (kind: 'openrouter_failure' | 'timeout' | 'context_too_long') => { if (!user) return; setBusy(true); try { const result = await simulateAIRouterFailure(user.id, kind); setSimulation(result); toast(result.success ? 'اكتمل اختبار الاستمرارية' : 'فشل اختبار الاستمرارية', result.success ? 'success' : 'error'); await load(); } catch (error: any) { toast(error.message, 'error'); } finally { setBusy(false); } };

  if (loading || !snapshot) return <div className="p-6"><Skeleton className="h-96" /></div>;
  const cards = [
    ['Fallbacks Today', snapshot.fallbacks_today, 'تحويلات اليوم'], ['Successful Recoveries', snapshot.successful_recoveries, 'استعادات ناجحة'], ['Failed Recoveries', snapshot.failed_recoveries, 'استعادات فاشلة'], ['Average AI Latency', `${snapshot.average_latency_ms} ms`, 'متوسط زمن الاستجابة'], ['Free Requests', snapshot.free_requests, 'طلبات مجانية'], ['Paid Requests', snapshot.paid_requests, 'طلبات مدفوعة'],
  ];

  return <div className="p-6 space-y-6 max-w-6xl mx-auto" dir="rtl">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold" style={{ color: 'rgb(var(--text-primary))' }}>AI Reliability Center</h1><p className="text-sm mt-1" style={{ color: 'rgb(var(--text-muted))' }}>Smart Router · Auto Failover · Context Preservation · Checkpointing</p></div><div className="flex gap-2"><Toggle checked={autoRefresh} onChange={setAutoRefresh} label="تحديث تلقائي" /><Button variant="secondary" onClick={load}><RefreshCw className="w-4 h-4" /> تحديث</Button></div></div>
    <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-3">{cards.map(([label, value, hint]) => <Card key={String(label)} className="p-4"><p className="text-xs" style={{ color: 'rgb(var(--text-muted))' }}>{label}</p><p className="text-2xl font-bold mt-2" style={{ color: 'rgb(var(--text-primary))' }}>{value}</p><p className="text-xs mt-1" style={{ color: 'rgb(var(--text-muted))' }}>{hint}</p></Card>)}</div>
    <Card className="p-5 space-y-4"><div><h2 className="font-bold" style={{ color: 'rgb(var(--text-primary))' }}>مفاتيح المزودين والتكاملات</h2><p className="text-sm mt-1" style={{ color: 'rgb(var(--text-muted))' }}>أدخل المفتاح هنا ثم اضغط حفظ واختبار الاتصال.</p></div><div className="grid md:grid-cols-2 gap-3">{aiProviders.map((provider) => <div key={provider.id} className="rounded-xl p-3 space-y-2" style={{ background: 'rgb(var(--bg-secondary))' }}><div className="flex justify-between"><span className="font-semibold">{provider.provider}</span><span className="text-xs" style={{ color: 'rgb(var(--text-muted))' }}>{provider.has_key ? 'مفتاح محفوظ' : 'غير مُعد'}</span></div><Input label="API Key" type="password" value={providerKeys[provider.id] ?? ''} onChange={(event) => setProviderKeys((current) => ({ ...current, [provider.id]: event.target.value }))} placeholder={provider.has_key ? 'اكتب مفتاحًا جديدًا للاستبدال' : 'ألصق المفتاح هنا'} /><Button variant="secondary" onClick={() => saveAndTestProvider(provider)} disabled={providerBusy === provider.id || !providerKeys[provider.id]?.trim()}>{providerBusy === provider.id ? 'جارٍ الحفظ والاختبار...' : 'حفظ واختبار الاتصال'}</Button></div>)}</div><div className="rounded-xl p-3 space-y-2" style={{ background: 'rgb(var(--bg-secondary))' }}><div className="flex justify-between"><span className="font-semibold">LinkedIn</span><span className="text-xs" style={{ color: 'rgb(var(--text-muted))' }}>{linkedinConnection ? 'اتصال محفوظ' : 'غير مُعد'}</span></div><Input label="Access Token" type="password" value={linkedinToken} onChange={(event) => setLinkedinToken(event.target.value)} placeholder="ألصق LinkedIn Access Token هنا" /><Button variant="secondary" onClick={saveLinkedinToken} disabled={linkedinBusy || !linkedinToken.trim()}>{linkedinBusy ? 'جارٍ الحفظ والاختبار...' : 'حفظ واختبار LinkedIn'}</Button><p className="text-xs" style={{ color: 'rgb(var(--text-muted))' }}>قبول التوكن لا يعني تلقائيًا امتلاك صلاحية البحث؛ البحث يحتاج موافقة LinkedIn Partner/API.</p></div></Card>
    <Card className="p-5"><div className="flex items-center justify-between mb-4"><div className="flex items-center gap-2"><ShieldCheck className="w-5 h-5" style={{ color: 'rgb(var(--success))' }} /><h2 className="font-bold" style={{ color: 'rgb(var(--text-primary))' }}>Provider Health</h2></div><Button variant="secondary" onClick={refreshModels} disabled={busy}><RefreshCw className="w-4 h-4" /> Refresh Models</Button></div><div className="grid md:grid-cols-2 xl:grid-cols-5 gap-3">{snapshot.providers.map((p) => <div key={p.id} className="rounded-xl p-3" style={{ background: 'rgb(var(--bg-secondary))' }}><div className="flex justify-between items-center"><span className="font-semibold">{p.provider}</span><Badge variant={statusVariant(p.status)}>{statusLabel[p.status] ?? p.status}</Badge></div><div className="grid grid-cols-2 gap-2 text-xs mt-3" style={{ color: 'rgb(var(--text-muted))' }}><span>نجاح: {p.success_rate}%</span><span>فشل: {p.failure_rate}%</span><span>زمن: {p.average_latency_ms}ms</span><span>طلبات: {p.requests_count}</span></div></div>)}</div></Card>
    <Card className="p-5"><div className="flex items-center gap-2 mb-4"><Activity className="w-5 h-5" style={{ color: 'rgb(var(--accent))' }} /><h2 className="font-bold" style={{ color: 'rgb(var(--text-primary))' }}>Free Model Pool</h2></div><div className="overflow-auto"><table className="w-full text-sm"><thead><tr className="text-right" style={{ color: 'rgb(var(--text-muted))' }}><th className="p-2">Model</th><th className="p-2">Context</th><th className="p-2">Capabilities</th><th className="p-2">Status</th><th className="p-2">Success</th><th className="p-2">Latency</th></tr></thead><tbody>{snapshot.models.filter((m) => m.is_free).slice(0, 30).map((m) => <tr key={m.id} className="border-t" style={{ borderColor: 'rgb(var(--border))' }}><td className="p-2 font-medium">{m.model}</td><td className="p-2">{m.context_length.toLocaleString()}</td><td className="p-2 max-w-xs truncate">{m.capabilities.slice(0, 4).join(', ') || 'text'}</td><td className="p-2"><Badge variant={statusVariant(m.status)}>{statusLabel[m.status] ?? m.status}</Badge></td><td className="p-2">{m.success_rate}%</td><td className="p-2">{m.average_latency_ms}ms</td></tr>)}</tbody></table>{snapshot.models.filter((m) => m.is_free).length === 0 && <p className="text-sm p-4 text-center" style={{ color: 'rgb(var(--text-muted))' }}>اضغط Refresh Models لجلب النماذج المجانية.</p>}</div></Card>
    <Card className="p-5"><div className="flex items-center gap-2 mb-4"><Zap className="w-5 h-5" style={{ color: 'rgb(var(--warning))' }} /><h2 className="font-bold" style={{ color: 'rgb(var(--text-primary))' }}>Failover Simulation</h2></div><p className="text-sm mb-4" style={{ color: 'rgb(var(--text-muted))' }}>اختبر أن المهمة تحفظ checkpoint وتستعيد السياق وتكمل من نفس الخطوة بدلاً من البدء من الصفر.</p><div className="flex flex-wrap gap-2">{([['openrouter_failure','Simulate OpenRouter Failure'],['timeout','Simulate Model Timeout'],['context_too_long','Simulate Context Compression']] as const).map(([kind, label]) => <Button key={kind} variant="secondary" onClick={() => runSimulation(kind)} disabled={busy}><RotateCcw className="w-4 h-4" />{label}</Button>)}</div>{simulation && <div className="mt-4 rounded-xl p-4" style={{ background: 'rgb(var(--bg-secondary))' }}><div className="flex items-center gap-2 mb-3">{simulation.success ? <CheckCircle2 className="w-5 h-5" style={{ color: 'rgb(var(--success))' }} /> : <AlertTriangle className="w-5 h-5" style={{ color: 'rgb(var(--danger))' }} />}<span className="font-semibold">{simulation.success ? 'Task Completed' : 'Recovery Failed'}</span></div><div className="flex flex-wrap gap-2">{(simulation.events ?? []).map((event) => <Badge key={event} variant={simulation.success ? 'success' : 'danger'}>{event}</Badge>)}</div></div>}</Card>
    <Card className="p-5"><h2 className="font-bold mb-3" style={{ color: 'rgb(var(--text-primary))' }}>Agent Console — آخر الأحداث</h2><div className="space-y-2 max-h-72 overflow-y-auto">{snapshot.events.slice(0, 40).map((event) => <div key={event.id} className="text-sm flex gap-2 items-start"><span className="text-xs min-w-32" style={{ color: 'rgb(var(--text-muted))' }}>{new Date(event.created_at).toLocaleTimeString('ar-EG')}</span><span>{event.message}</span>{event.error_type && <Badge variant="warning">{event.error_type}</Badge>}</div>)}{snapshot.events.length === 0 && <p className="text-sm" style={{ color: 'rgb(var(--text-muted))' }}>لا توجد أحداث بعد.</p>}</div></Card>
  </div>;
}
